language: swift
os: osx
osx_image: xcode10.1
env: SWIFT_SNAPSHOT=4.2

cache: cocoapods

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - XCODE_WORKSPACE=./J2M.xcworkspace
  matrix:
    - SCHEME=J2M
    - SCHEME=J2M-Demo
    - SCHEME=J2MTests
    - SCHEME=J2M-macOS
    - SCHEME=J2M-macOS-Demo
    - SCHEME=J2MTests-macOS
    - SCHEME=J2M-tvOS
    - SCHEME=J2M-tvOS-Demo
    - SCHEME=J2MTests-tvOS

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet

script:
  - |
    set -o pipefail;
    if [ "$SCHEME" = J2M ]; then
      xcodebuild clean test -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -destination 'platform=iOS Simulator,name=iPhone 7,OS=12.0' -configuration Release ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES | xcpretty -c;
    elif [ "$SCHEME" = J2M-Demo ]; then
      xcodebuild clean test -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -destination 'platform=iOS Simulator,name=iPhone 7,OS=12.0' -configuration Release ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES | xcpretty -c;
    elif [ "$SCHEME" = J2M-Demo ]; then
      xcodebuild clean test -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -destination 'platform=iOS Simulator,name=iPhone 7,OS=12.0' -configuration Release ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES | xcpretty -c;
    elif [ "$SCHEME" = J2M-macOS ]; then
      xcodebuild clean test -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -sdk macosx -configuration Release ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES | xcpretty -c;
    elif [ "$SCHEME" = J2M-macOS-Demo ]; then
      xcodebuild clean test -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -sdk macosx -configuration Release ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES | xcpretty -c;
    elif [ "$SCHEME" = J2MTests-macOS ]; then
      xcodebuild clean test -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -sdk macosx -configuration Release ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES | xcpretty -c;
    elif [ "$SCHEME" = J2M-tvOS ]; then
      xcodebuild clean test -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -destination "platform=tvOS Simulator,name=Apple TV,OS=12.0" -configuration Release ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES | xcpretty -c;
    elif [ "$SCHEME" = J2M-tvOS-Demo ]; then
      xcodebuild clean test -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -destination "platform=tvOS Simulator,name=Apple TV,OS=12.0" -configuration Release ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES | xcpretty -c;
    elif [ "$SCHEME" = J2MTests-tvOS ]; then
      xcodebuild clean test -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -destination "platform=tvOS Simulator,name=Apple TV,OS=12.0" -configuration Release ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES | xcpretty -c;
    fi
  - pod lib lint --allow-warnings

after_success:
  - sleep 3
  - bash <(curl -s https://codecov.io/bash)