language: objective-c
os: osx
osx_image: xcode10
env: SWIFT_SNAPSHOT=4.2

env:
  matrix:
    - TEST_TYPE=iOS
    - TEST_TYPE=macOS
    - TEST_TYPE=tvOS
-before_install:
 - |
    gem install xcpretty -N --no-ri --no-rdoc
script:
- |
    if [ "$TEST_TYPE" = iOS ]; then
      set -o pipefail
      xcodebuild clean test -workspace J2M.xcworkspace -scheme J2M -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.0' -enableCodeCoverage YES | xcpretty
    elif [ "$TEST_TYPE" = macOS ]; then
      set -o pipefail
      xcodebuild clean test -workspace J2M.xcworkspace -scheme J2M-macOS -sdk macosx -enableCodeCoverage YES | xcpretty
    elif [ "$TEST_TYPE" = tvOS ]; then
      set -o pipefail
      xcodebuild clean test -workspace J2M.xcworkspace -scheme J2M-tvOS -destination "platform=tvOS Simulator,name=Apple TV 1080p" -enableCodeCoverage YES | xcpretty
    fi
after_success:
    - sleep 5
    - if [ "$TEST_TYPE" = iOS ] || [ "$TEST_TYPE" = macOS ] || [ "$TEST_TYPE" = tvOS ]; then
        bash <(curl -s https://codecov.io/bash)
      fi
