language: objective-c
os: osx
osx_image: xcode10
env: SWIFT_SNAPSHOT=4.2

cache: cocoapods

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
  matrix:
    - TEST_TYPE=iOS
    - TEST_TYPE=macOS
    - TEST_TYPE=tvOS

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet

script:
  - |
    set -o pipefail
    if [ "$TEST_TYPE" = iOS ]; then
      xcodebuild clean test -workspace J2M.xcworkspace -scheme J2M -destination 'platform=iOS Simulator,name=iPhone 7,OS=12.0' -enableCodeCoverage YES | xcpretty;
      xcodebuild clean test -workspace J2M.xcworkspace -scheme J2M-Demo -destination 'platform=iOS Simulator,name=iPhone 7,OS=12.0' -enableCodeCoverage YES | xcpretty;
      xcodebuild clean test -workspace J2M.xcworkspace -scheme J2MTests -destination 'platform=iOS Simulator,name=iPhone 7,OS=12.0' -enableCodeCoverage YES | xcpretty;
    elif [ "$TEST_TYPE" = macOS ]; then
      xcodebuild clean test -workspace J2M.xcworkspace -scheme J2M-macOS -sdk macosx -enableCodeCoverage YES | xcpretty;
      xcodebuild clean test -workspace J2M.xcworkspace -scheme J2M-macOS-Demo -sdk macosx -enableCodeCoverage YES | xcpretty;
      xcodebuild clean test -workspace J2M.xcworkspace -scheme J2MTests-macOS -sdk macosx -enableCodeCoverage YES | xcpretty;
    elif [ "$TEST_TYPE" = tvOS ]; then
      xcodebuild clean test -workspace J2M.xcworkspace -scheme J2M-tvOS -destination "platform=tvOS Simulator,name=Apple TV,OS=12.0" -enableCodeCoverage YES | xcpretty;
      xcodebuild clean test -workspace J2M.xcworkspace -scheme J2M-tvOS-Demo -destination "platform=tvOS Simulator,name=Apple TV,OS=12.0" -enableCodeCoverage YES | xcpretty;
      xcodebuild clean test -workspace J2M.xcworkspace -scheme J2MTests-tvOS -destination "platform=tvOS Simulator,name=Apple TV,OS=12.0" -enableCodeCoverage YES | xcpretty;
    fi
  - pod lib lint --allow-warnings

after_success:
  - sleep 5
  - if [ "$TEST_TYPE" = iOS ] || [ "$TEST_TYPE" = macOS ] || [ "$TEST_TYPE" = tvOS ]; then
      bash <(curl -s https://codecov.io/bash) -J 'J2M' -J 'J2M-macOS' -J 'J2M-tvOS'
    fi